

urls:
  profile: http://localhost:8081
  course: http://localhost:8082
server:
  port: 8084
keys:
  pri: classpath:keys/private.pem
  pub: classpath:keys/public.pem

spring:
  datasource:
#    url: jdbc:h2:mem:profile
#    driver-class-name: org.h2.Driver
    username: profile
    password: nQmRmIgG8Zo
    url: jdbc:postgresql://localhost:5432/enrollment
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:keys/public.pem
  jpa:
    hibernate:
      ddl-auto: update